### ISSUE TITLE
My testing code is crashed.

### ISSUE THREAD

**Issue by gergul** [PerMalmberg/libcron#15]
`#include <libcron/Cron.h>
#include <date/date.h>
#include <thread>

void foo(libcron::Cron<>& c)
{
	auto expired = false;

	c.add_schedule("task2", "* * * * * ?",
		[&expired](auto&)
	{
		expired = true;
	});
}

void main()
{
	libcron::Cron<> c1;
	foo(c1);
	
	libcron::Cron<> c2;
	foo(c2);

	while (true)
	{
		c1.tick();
		c2.tick();
		std::this_thread::sleep_for(std::chrono::milliseconds(500));
	}
}`
windows10 x64 vs2015

**Comment by PerMalmberg** [comment]
Yes, don't access memory no longer owned by your application. Closing this as it's not a problem with libcron.
