### ISSUE TITLE
Allow ”convenice scheduling”, e.g. @daily.

### ISSUE THREAD

**Issue by peter-jansson** [PerMalmberg/libcron#20]
https://github.com/PerMalmberg/libcron/blob/e91a51afc1d3e0ef2de8849e6c7bd84dd45d0ad9/libcron/src/CronData.cpp#L41

Some versions of Cron allow such convenience names, e.g. using @daily or @hourly. Perhaps it could be useful in this library too.

**Comment by PerMalmberg** [comment]
It would. Feel free to make a PR for such functionality.
