### ISSUE TITLE
Not a bug. Playground with cron expressions

### ISSUE THREAD

**Issue by clabnet** [PerMalmberg/libcron#21]
Hi, 
there are a lot of tools online generator for cron expressions .
I have tried a couple but I'm not sure its "talking" the same dialect of cron expression of this code. 
Could you please suggest an online generator to test the cron strings  surely **compliant to this program** ?
Thank's for this code.

**Comment by PerMalmberg** [comment]
I have no idea, I don't use any online cron generators.

What expressions are you having problems with?

**Comment by clabnet** [comment]
No, not a problem, my simple cron expression is 0 */10 * * * ? to fire event each 10 minutes.
I have used these sites:
- http://www.cronmaker.com/?1
- https://www.freeformatter.com/cron-expression-generator-quartz.html
Its seems ok. But NOT https://crontab.guru, because this not support the last parameter (weekday).

**Comment by PerMalmberg** [comment]
I write my cron expressions by hand.

Anyway, seems this issue is solved. So I'll close it.
