### ISSUE TITLE
Support of `make install`...?

### ISSUE THREAD

**Issue by VergeDX** [PerMalmberg/libcron#22]
Hi, I'm a packager of NixOS, I'm packaging https://github.com/tindy2013/subconverter which used your libcron library.
So I need packing libcron first. I noticed there is no install phase here, like `make install`.
subconverter solves this issues by using `install` manually: https://github.com/tindy2013/subconverter/blob/v0.7.1/scripts/config.termux.sh#L34.
But if we have one that will be better! I can help for making PR.

**Comment by PerMalmberg** [comment]
>  I can help for making PR.
Go ahead.
