### ISSUE TITLE
Linking QT library causes regular expression matching to fail

### ISSUE THREAD

**Issue by qyy-wakaka** [PerMalmberg/libcron#35]
When using libcron, CronData:: create failed, and it was found that if libQt5Coreuarm64 v8a. so and
LibQt5Gui-arm64 v8a. so will encounter problems, and if these two Qt libraries are not linked, there will be no problem. If these two libraries are linked, there is an issue with regular expression matching: CronData:: part cannot be executed in if (std:: regex_match (expression. begin(), expression. end(), match, split)). If changed to std:: regex split {R "# (\s*(.*?)\s+(.*?)) #", std::regex_constants::ECMAScript }; It can only be executed normally in if (std:: regex_match (expression. begin(), expression. end(), match, split)), but this is only possible and the logic is incorrect.
May I ask how to solve this problem.
![image](https://github.com/PerMalmberg/libcron/assets/52314176/98a3277c-36fa-4188-a0c1-014b0c633534)

**Comment by PerMalmberg** [comment]
So if you link `LibQt*.so` it no longer compiles, or does the regex matching fail at runtime when they are linked? I can't tell from the problem description.

**Comment by qyy-wakaka** [comment]
Can compile normally, but cannot run properly. Std:: regex_match condition not met.

**Comment by PerMalmberg** [comment]
Is this when running the tests (do they pass?) or your cron expressions?

**Comment by qyy-wakaka** [comment]
My project includes libQtxxx.so, and this time I want to add libcron. If there is only libcron in the project, there is no problem, but after linking libQtxxx.so, the problem arises. My project includes libQtxxx.so. I have encountered similar issues using std:: regex before, but it has nothing to do with libcron. It just hasn't been resolved yet. I would like to ask if there are any new ideas.

**Comment by PerMalmberg** [comment]
So QT somehow affects std::regex. Try a different link order, maybe?

**Comment by sc-bai** [comment]
![微信图片_20240716101348](https://github.com/user-attachments/assets/5deffa7f-d596-45e6-8f0b-d38e7ab59abd)

Are there any files missing?

**Comment by PerMalmberg** [comment]
> Are there any files missing?

No, did you get the Git submodules?

Closing this issue as original author has not been responding for three weeks.

**Comment by sc-bai** [comment]
> > Are there any files missing?
> 
> No, did you get the Git submodules?
> 
> Closing this issue as original author has not been responding for three weeks.

I Got it. readme with last infos.
