### ISSUE TITLE
Adding once a minute to examples on main page documentation

### ISSUE THREAD

**Issue by nkinar** [PerMalmberg/libcron#36]
Would it be possible to add an example for once a minute to the main page documentation?  In the table, perhaps a string such as

"0 * * * * ?"

I feel that this would be very helpful in the main documentation.  Thanks for your great library.

**Comment by PerMalmberg** [comment]
Sure, make a PR.

**Comment by nkinar** [comment]
Here is the PR.  Thanks for the opportunity to contribute to the documentation.

https://github.com/PerMalmberg/libcron/pull/37
