### ISSUE TITLE
almalinux 9.4 compile error

### ISSUE THREAD

**Issue by spacexnasa** [PerMalmberg/libcron#39]
has been install catch-devel 

-- The C compiler identification is GNU 11.4.1
-- The CXX compiler identification is GNU 11.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/software/libcron
[  9%] Building CXX object libcron/CMakeFiles/libcron.dir/src/CronClock.cpp.o
[ 18%] Building CXX object libcron/CMakeFiles/libcron.dir/src/Task.cpp.o
[ 27%] Building CXX object libcron/CMakeFiles/libcron.dir/src/CronRandomization.cpp.o
[ 36%] Building CXX object libcron/CMakeFiles/libcron.dir/src/CronData.cpp.o
[ 45%] Building CXX object libcron/CMakeFiles/libcron.dir/src/CronSchedule.cpp.o
[ 54%] Linking CXX static library out/Release/liblibcron.a
[ 54%] Built target libcron
[ 63%] Building CXX object test/CMakeFiles/cron_test.dir/CronScheduleTest.cpp.o
[ 81%] Building CXX object test/CMakeFiles/cron_test.dir/CronDataTest.cpp.o
[ 81%] Building CXX object test/CMakeFiles/cron_test.dir/CronRandomizationTest.cpp.o
[ 90%] Building CXX object test/CMakeFiles/cron_test.dir/CronTest.cpp.o
/home/software/libcron/test/CronScheduleTest.cpp:1:10: fatal error: catch.hpp: No such file or directory
    1 | #include <catch.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [test/CMakeFiles/cron_test.dir/build.make:104: test/CMakeFiles/cron_test.dir/CronScheduleTest.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/software/libcron/test/CronRandomizationTest.cpp:1:10: fatal error: catch.hpp: No such file or directory
    1 | #include <catch.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
/home/software/libcron/test/CronDataTest.cpp:3:10: fatal error: catch.hpp: No such file or directory
    3 | #include <catch.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [test/CMakeFiles/cron_test.dir/build.make:90: test/CMakeFiles/cron_test.dir/CronRandomizationTest.cpp.o] Error 1
make[2]: *** [test/CMakeFiles/cron_test.dir/build.make:76: test/CMakeFiles/cron_test.dir/CronDataTest.cpp.o] Error 1
/home/software/libcron/test/CronTest.cpp:1:10: fatal error: catch.hpp: No such file or directory
    1 | #include <catch.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [test/CMakeFiles/cron_test.dir/build.make:118: test/CMakeFiles/cron_test.dir/CronTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: test/CMakeFiles/cron_test.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by PerMalmberg** [comment]
Update your git submodule. 

https://github.com/PerMalmberg/libcron/tree/master/test/externals
