### ISSUE TITLE
Modernize the code

### ISSUE THREAD

**Issue by GitSparTV** [PerMalmberg/libcron#42]
CMake file sets C++17 standard however the code doesn't use neither features from C++17 (`<charconv>`), nor from C++11 (`constexpr`).

Consider upgrading for better performance.
Not to mention, that `std::to_string` is weird because it uses user locale for numbers. (`sprintf` internally)

**Comment by PerMalmberg** [comment]
Feel free to make a PR with tests proving updated code fixes an actual issue.
