### ISSUE TITLE
Some standard cron expressions don't work yet are considered valid

### ISSUE THREAD

**Issue by l0go** [PerMalmberg/libcron#44]
Not really an issue, but no clue where else to post this. Some context: I am trying to convert generated cron expressions into ones that can be understood by libcron. Right now I am confused on why using six asterisks (``* * * * * *``) doesn't run every second like in most cron implementations? I am guessing libcron doesn't try to maintain compatibility with other schedulers?

**Comment by PerMalmberg** [comment]
From the readme:

> Day of month and day of week are mutually exclusive so one of them must at always be ignored using the '?'-character to ensure that it is not possible to specify a statement which results in an impossible mix of these fields.

**Comment by l0go** [comment]
Thank you so much!
Don't know how I missed it. Everything works now. Outside of my initial confusion this has been a great library to work with.
