### ISSUE TITLE
libcron make error

### ISSUE THREAD

**Issue by testwill** [PerMalmberg/libcron#45]
make
Scanning dependencies of target libcron
[ 16%] Building CXX object CMakeFiles/libcron.dir/src/CronClock.cpp.o
[ 33%] Building CXX object CMakeFiles/libcron.dir/src/CronData.cpp.o
/home/ggw/libcron-1.3.1/libcron/src/CronData.cpp:1:10: fatal error: date/date.h: No such file or directory
 #include <date/date.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/libcron.dir/build.make:76: CMakeFiles/libcron.dir/src/CronData.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/libcron.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by PerMalmberg** [comment]
https://github.com/PerMalmberg/libcron/blob/master/.gitmodules

Checkout Git submodules too.
